//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Junior.Route.Diagnostics.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Junior.Route.Diagnostics.Web.ResponseResources", typeof(ResponseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Application {
            get {
                object obj = ResourceManager.GetObject("Application", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///	color: #000;
        ///	font-size: 16px;
        ///	font-family: Helvetica, sans-serif;
        ///}
        ///h1
        ///{
        ///	font-family: Georgia, serif;
        ///	font-size: 2em;
        ///	font-weight: normal;
        ///	margin-bottom: 10px;
        ///}
        ///h1:not(:first-child)
        ///{
        ///	margin-top: 20px;
        ///}
        ///input[type=&apos;checkbox&apos;]
        ///{
        ///	vertical-align: middle;
        ///	margin-right: 5px;
        ///}
        ///
        ///#header
        ///{
        ///	background-color: #eee;
        ///	font-size: 0.8em;
        ///	padding: 5px;
        ///}
        ///#header-left
        ///{
        ///	float: left;
        ///}
        ///#header-right
        ///{
        ///	text-align: right;
        ///}
        ///#body
        ///{
        ///	padding: 10px;
        ///}
        ///
        ///.header-li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string common {
            get {
                return ResourceManager.GetString("common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Diagnostics {
            get {
                object obj = ResourceManager.GetObject("Diagnostics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.8.2 jquery.com | jquery.org/license */
        ///(function(a,b){function G(a){var b=F[a]={};return p.each(a.split(s),function(a,c){b[c]=!0}),b}function J(a,c,d){if(d===b&amp;&amp;a.nodeType===1){var e=&quot;data-&quot;+c.replace(I,&quot;-$1&quot;).toLowerCase();d=a.getAttribute(e);if(typeof d==&quot;string&quot;){try{d=d===&quot;true&quot;?!0:d===&quot;false&quot;?!1:d===&quot;null&quot;?null:+d+&quot;&quot;===d?+d:H.test(d)?p.parseJSON(d):d}catch(f){}p.data(a,c,d)}else d=b}return d}function K(a){var b;for(b in a){if(b===&quot;data&quot;&amp;&amp;p.isEmptyObject(a[b]))continue;if(b!==&quot;toJSON&quot;)ret [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_8_2_min {
            get {
                return ResourceManager.GetString("jquery_1_8_2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///	HTML5 Reset :: style.css
        ///	----------------------------------------------------------
        ///	We have learned much from/been inspired by/taken code where offered from:
        ///	
        ///	Eric Meyer					:: http://ericmeyer.com
        ///	HTML5 Doctor				:: http://html5doctor.com
        ///	and the HTML5 Boilerplate	:: http://html5boilerplate.com
        ///	
        ///-------------------------------------------------------------------------------*/
        ///
        ////* Let&apos;s default this puppy out
        ///---------------------------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
    }
}
