//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Junior.Route.Routing.Diagnostics.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Junior.Route.Routing.Diagnostics.Web.ResponseResources", typeof(ResponseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .route-table-view td
        ///{
        ///	border-collapse: collapse;
        ///	padding: 2px 5px;
        ///}
        ///.route-table-view thead td
        ///{
        ///	border: 1px solid #bbb;
        ///	font-weight: bold;
        ///	text-align: center;
        ///	vertical-align: middle;
        ///}
        ///.route-table-view tbody td
        ///{
        ///	border: 1px solid #ddd;
        ///}
        ///.route-table-view .name-header,
        ///.route-table-view .id-header
        ///{
        ///	background-color: #eee;
        ///	display: none;
        ///}
        ///.route-table-view .name-data,
        ///.route-table-view .id-data
        ///{
        ///	display: none;
        ///}
        ///.route-table-view .resolved-relative-url-header
        ///{
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string route_table_view {
            get {
                return ResourceManager.GetString("route_table_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RouteTable {
            get {
                object obj = ResourceManager.GetObject("RouteTable", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
