//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NathanAlden.JuniorRouting.Diagnostics.Responses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NathanAlden.JuniorRouting.Diagnostics.Responses.ResponseResources", typeof(ResponseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Application {
            get {
                object obj = ResourceManager.GetObject("Application", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///	color: #000;
        ///	font-size: 16px;
        ///	font-family: Helvetica, sans-serif;
        ///}
        ///h1
        ///{
        ///	font-family: Georgia, serif;
        ///	font-size: 2em;
        ///	font-weight: normal;
        ///	padding-bottom: 10px;
        ///}
        ///
        ///#header
        ///{
        ///	background-color: #ddd;
        ///	font-size: 0.8em;
        ///	padding: 5px;
        ///}
        ///#header-links
        ///{
        ///	float: left;
        ///}
        ///#header-info
        ///{
        ///	text-align: right;
        ///}
        ///#body
        ///{
        ///	padding: 10px;
        ///}
        ///
        ///.invisible
        ///{
        ///	display: none;
        ///}
        ///.centered
        ///{
        ///	text-align: center;
        ///}
        ///.no-wrap
        ///{
        ///	white-space: nowrap;
        ///}.
        /// </summary>
        internal static string common {
            get {
                return ResourceManager.GetString("common", resourceCulture);
            }
        }
        
        internal static byte[] Diagnostics {
            get {
                object obj = ResourceManager.GetObject("Diagnostics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///	HTML5 Reset :: style.css
        ///	----------------------------------------------------------
        ///	We have learned much from/been inspired by/taken code where offered from:
        ///	
        ///	Eric Meyer					:: http://ericmeyer.com
        ///	HTML5 Doctor				:: http://html5doctor.com
        ///	and the HTML5 Boilerplate	:: http://html5boilerplate.com
        ///	
        ///-------------------------------------------------------------------------------*/
        ///
        ////* Let&apos;s default this puppy out
        ///---------------------------------------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .route-table-view td
        ///{
        ///	border-collapse: collapse;
        ///	padding: 2px 5px;
        ///}
        ///.route-table-view thead td
        ///{
        ///	background-color: #ddd;
        ///	border: 1px solid #bbb;
        ///	font-weight: bold;
        ///	text-align: center;
        ///	vertical-align: middle;
        ///}
        ///.route-table-view tbody td
        ///{
        ///	border: 1px solid #ddd;
        ///}
        ///.route-table-view .flags-table
        ///{
        ///	width: 100%;
        ///}
        ///.route-table-view .flags-table td:first-child
        ///{
        ///	width: 100%;
        ///}
        ///.route-table-view .flags-table td
        ///{
        ///	border: 0;
        ///	padding: 0;
        ///}
        ///.route-table-view .flags
        ///{
        ///	p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string route_table_view {
            get {
                return ResourceManager.GetString("route_table_view", resourceCulture);
            }
        }
        
        internal static byte[] RouteTable {
            get {
                object obj = ResourceManager.GetObject("RouteTable", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
