using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly:ComVisible(false)]
[assembly:AssemblyVersion("0.9.0.0")]
[assembly:AssemblyFileVersion("0.9.0.0")]
[assembly:AssemblyInformationalVersion("0.9.0.0")]